- title: "Ghostty的配置与使用"
  date: "2026-03-31 23:17:16"
  tags:
    - "Ghostty"
- title: "Homebrew的安装和使用"
  date: "2023-07-21 02:37:29"
  tags:
    - "Homebrew"
- title: "macOS的快捷键与常用软件"
  date: "2023-07-21 02:37:29"
  tags:
    - "macOS"
